INSERT INTO de3at.PAKS_DWH_FACT_TRANSACTIONS (
    TRANSACTION_ID, TRANSACTION_DATE, AMOUNT, CARD_NUM, OPERATION_TYPE, OPERATION_RESULT, TERMINAL_ID
) SELECT TRANSACTION_ID, TRANSACTION_DATE, AMOUNT, CARD_NUM, OPERATION_TYPE, OPERATION_RESULT, TERMINAL_ID
    FROM DE3AT.PAKS_STG_TRANSACTIONS
    WHERE TRANSACTION_DATE > (
        SELECT LAST_UPDATE_DT
        FROM PAKS_META_DATA
        WHERE SCHEMA_NAME='DE3AT' AND TABLE_NAME='TRANSACTIONS'
    );

UPDATE DE3AT.PAKS_META_DATA
SET LAST_UPDATE_DT = (SELECT MAX(TRANSACTION_DATE) FROM DE3AT.PAKS_DWH_FACT_TRANSACTIONS)
WHERE SCHEMA_NAME='DE3AT' AND TABLE_NAME='TRANSACTIONS';

COMMIT;
