DELETE FROM DE3AT.PAKS_STG_CLIENTS_DEL WHERE 1=1;
COMMIT;

INSERT INTO DE3AT.PAKS_STG_CLIENTS_DEL (CLIENT_ID) SELECT CLIENT_ID FROM BANK.CLIENTS;

-- забираем изменения с последнего момента
INSERT INTO DE3AT.PAKS_STG_CLIENTS (
    CLIENT_ID, LAST_NAME, FIRST_NAME, PATRONYMIC,
    DATE_OF_BIRTH, PASSPORT_NUM, PASSPORT_VALID_TO, PHONE,
    UPDATE_DT, STAGE_DT)
SELECT CLIENT_ID, LAST_NAME, FIRST_NAME, PATRONYMIC,
       DATE_OF_BIRTH, PASSPORT_NUM, PASSPORT_VALID_TO, PHONE,
       COALESCE(UPDATE_DT, CREATE_DT), CURRENT_DATE FROM BANK.CLIENTS
WHERE COALESCE(UPDATE_DT, CREATE_DT) > COALESCE(
    (
        SELECT LAST_UPDATE_DT
        FROM DE3AT.PAKS_META_DATA
        WHERE SCHEMA_NAME='DE3AT' AND TABLE_NAME='CLIENTS'
    ),
    TO_DATE('1900-01-01 00:00:00', 'HH24:MI:SS')
);

-- 2. Выделение вставок и изменений (transform), вставка в их приемник (load)
INSERT INTO DE3AT.PAKS_DWH_DIM_CLIENTS_HIST (
    CLIENT_ID, LAST_NAME, FIRST_NAME, PATRONYMIC
    , DATE_OF_BIRTH, PASSPORT_NUM, PASSPORT_VALID_TO, PHONE
    , EFFECTIVE_FROM, EFFECTIVE_TO, DELETED_FLG)
SELECT
    STG.CLIENT_ID, STG.LAST_NAME, STG.FIRST_NAME, STG.PATRONYMIC,
    STG.DATE_OF_BIRTH, STG.PASSPORT_NUM, STG.PASSPORT_VALID_TO, STG.PHONE,
    STG.UPDATE_DT,
    TO_DATE('2999-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'),
    'N'
FROM DE3AT.PAKS_DWH_DIM_CLIENTS_HIST TRG
INNER JOIN DE3AT.PAKS_STG_CLIENTS STG
ON (
    TRG.CLIENT_ID = STG.CLIENT_ID
    AND TRG.EFFECTIVE_TO = TO_DATE('2999-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS')
    AND TRG.DELETED_FLG = 'N')
WHERE 1 = 1
    AND STG.UPDATE_DT > (
        SELECT LAST_UPDATE_DT
        FROM DE3AT.PAKS_META_DATA
        WHERE SCHEMA_NAME='DE3AT' AND TABLE_NAME='CLIENTS')
    AND (1 = 0
--          CLIENT_ID, LAST_NAME, FIRST_NAME, PATRONYMIC
--     , DATE_OF_BIRTH, PASSPORT_NUM, PASSPORT_VALID_TO, PHONE
        OR STG.LAST_NAME <> TRG.LAST_NAME
        OR STG.FIRST_NAME <> TRG.FIRST_NAME
        OR STG.PATRONYMIC <> TRG.PATRONYMIC
        OR STG.DATE_OF_BIRTH <> TRG.DATE_OF_BIRTH
        OR STG.PASSPORT_NUM <> TRG.PASSPORT_NUM
        OR STG.PASSPORT_VALID_TO <> TRG.PASSPORT_VALID_TO
        OR STG.PHONE <> TRG.PHONE
        OR (STG.LAST_NAME IS NULL AND TRG.LAST_NAME IS NOT NULL)
        OR (STG.FIRST_NAME IS NULL AND TRG.FIRST_NAME IS NOT NULL)
        OR (STG.PATRONYMIC IS NULL AND TRG.PATRONYMIC IS NOT NULL)
        OR (STG.DATE_OF_BIRTH IS NULL AND TRG.DATE_OF_BIRTH IS NOT NULL)
        OR (STG.PASSPORT_NUM IS NULL AND TRG.PASSPORT_NUM IS NOT NULL)
        OR (STG.PASSPORT_VALID_TO IS NULL AND TRG.PASSPORT_VALID_TO IS NOT NULL)
        OR (STG.PHONE IS NULL AND TRG.PHONE IS NOT NULL)
        OR (STG.LAST_NAME IS NOT NULL AND TRG.LAST_NAME IS NULL)
        OR (STG.FIRST_NAME IS NOT NULL AND TRG.FIRST_NAME IS NULL)
        OR (STG.PATRONYMIC IS NOT NULL AND TRG.PATRONYMIC IS NULL)
        OR (STG.DATE_OF_BIRTH IS NOT NULL AND TRG.DATE_OF_BIRTH IS NULL)
        OR (STG.PASSPORT_NUM IS NOT NULL AND TRG.PASSPORT_NUM IS NULL)
        OR (STG.PASSPORT_VALID_TO IS NOT NULL AND TRG.PASSPORT_VALID_TO IS NULL)
        OR (STG.PHONE IS NOT NULL AND TRG.PHONE IS NULL)
    );

MERGE INTO DE3AT.PAKS_DWH_DIM_CLIENTS_HIST TRG
USING DE3AT.PAKS_STG_CLIENTS STG
ON (STG.CLIENT_ID = TRG.CLIENT_ID
    AND TRG.DELETED_FLG = 'N'
    AND STG.UPDATE_DT > (
        SELECT LAST_UPDATE_DT
        FROM DE3AT.PAKS_META_DATA
        WHERE SCHEMA_NAME='DE3AT' AND TABLE_NAME='CLIENTS'
    )
)
WHEN MATCHED THEN
    UPDATE SET TRG.EFFECTIVE_TO = UPDATE_DT - INTERVAL  '1' SECOND
    WHERE TRG.EFFECTIVE_TO = TO_DATE('2999-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS')
    AND (1 = 0
        OR STG.LAST_NAME <> TRG.LAST_NAME
        OR STG.FIRST_NAME <> TRG.FIRST_NAME
        OR STG.PATRONYMIC <> TRG.PATRONYMIC
        OR STG.DATE_OF_BIRTH <> TRG.DATE_OF_BIRTH
        OR STG.PASSPORT_NUM <> TRG.PASSPORT_NUM
        OR STG.PASSPORT_VALID_TO <> TRG.PASSPORT_VALID_TO
        OR STG.PHONE <> TRG.PHONE
        OR (STG.LAST_NAME IS NULL AND TRG.LAST_NAME IS NOT NULL)
        OR (STG.FIRST_NAME IS NULL AND TRG.FIRST_NAME IS NOT NULL)
        OR (STG.PATRONYMIC IS NULL AND TRG.PATRONYMIC IS NOT NULL)
        OR (STG.DATE_OF_BIRTH IS NULL AND TRG.DATE_OF_BIRTH IS NOT NULL)
        OR (STG.PASSPORT_NUM IS NULL AND TRG.PASSPORT_NUM IS NOT NULL)
        OR (STG.PASSPORT_VALID_TO IS NULL AND TRG.PASSPORT_VALID_TO IS NOT NULL)
        OR (STG.PHONE IS NULL AND TRG.PHONE IS NOT NULL)
        OR (STG.LAST_NAME IS NOT NULL AND TRG.LAST_NAME IS NULL)
        OR (STG.FIRST_NAME IS NOT NULL AND TRG.FIRST_NAME IS NULL)
        OR (STG.PATRONYMIC IS NOT NULL AND TRG.PATRONYMIC IS NULL)
        OR (STG.DATE_OF_BIRTH IS NOT NULL AND TRG.DATE_OF_BIRTH IS NULL)
        OR (STG.PASSPORT_NUM IS NOT NULL AND TRG.PASSPORT_NUM IS NULL)
        OR (STG.PASSPORT_VALID_TO IS NOT NULL AND TRG.PASSPORT_VALID_TO IS NULL)
        OR (STG.PHONE IS NOT NULL AND TRG.PHONE IS NULL)
    )
WHEN NOT MATCHED THEN
    INSERT (
        CLIENT_ID, LAST_NAME, FIRST_NAME, PATRONYMIC
        , DATE_OF_BIRTH, PASSPORT_NUM, PASSPORT_VALID_TO, PHONE
        , EFFECTIVE_FROM, EFFECTIVE_TO, DELETED_FLG)
    VALUES (
        STG.CLIENT_ID,
        STG.LAST_NAME,
        STG.FIRST_NAME,
        STG.PATRONYMIC,
        STG.DATE_OF_BIRTH,
        STG.PASSPORT_NUM,
        STG.PASSPORT_VALID_TO,
        STG.PHONE,
        STG.UPDATE_DT,
        TO_DATE('2999-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'),
        'N'
    ) WHERE COALESCE(STG.UPDATE_DT, STG.CREATE_DT) > (
        SELECT LAST_UPDATE_DT
        FROM DE3AT.PAKS_META_DATA
        WHERE SCHEMA_NAME='DE3AT' AND TABLE_NAME='CLIENTS');

-- 3. Обработка удалений.
INSERT INTO DE3AT.PAKS_DWH_DIM_CLIENTS_HIST (
    CLIENT_ID, LAST_NAME, FIRST_NAME, PATRONYMIC
    , DATE_OF_BIRTH, PASSPORT_NUM, PASSPORT_VALID_TO, PHONE
    , EFFECTIVE_FROM, EFFECTIVE_TO, DELETED_FLG
) SELECT TRG.CLIENT_ID,
        TRG.LAST_NAME,
        TRG.FIRST_NAME,
        TRG.PATRONYMIC,
        TRG.DATE_OF_BIRTH,
        TRG.PASSPORT_NUM,
        TRG.PASSPORT_VALID_TO,
        TRG.PHONE,
        CURRENT_DATE,
        TO_DATE('2999-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'),
        'Y'
FROM DE3AT.PAKS_DWH_DIM_CLIENTS_HIST TRG
    LEFT JOIN DE3AT.PAKS_STG_CLIENTS_DEL DEL
    ON (
        DEL.CLIENT_ID=TRG.CLIENT_ID
        AND TRG.EFFECTIVE_TO = TO_DATE('2999-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS')
        AND DELETED_FLG = 'N')
WHERE
      DEL.CLIENT_ID IS NULL
      AND TRG.DELETED_FLG = 'N'
      AND CURRENT_DATE BETWEEN TRG.EFFECTIVE_FROM AND TRG.EFFECTIVE_TO ;


UPDATE DE3AT.PAKS_DWH_DIM_CLIENTS_HIST TRG
SET EFFECTIVE_TO = CURRENT_DATE - INTERVAL  '1' SECOND
WHERE 1 = 1
    AND TRG.CLIENT_ID NOT IN (
        SELECT DEL.CLIENT_ID FROM DE3AT.PAKS_STG_CLIENTS_DEL DEL
    )
    AND TRG.EFFECTIVE_TO = TO_DATE('2999-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS')
    AND TRG.DELETED_FLG = 'N';

-- 4. Обновление метаданных.

UPDATE DE3AT.PAKS_META_DATA
SET LAST_UPDATE_DT = (SELECT MAX(UPDATE_DT) FROM DE3AT.PAKS_STG_CLIENTS)
WHERE SCHEMA_NAME='DE3AT' AND TABLE_NAME='CLIENTS';

COMMIT;
