INSERT INTO DE3AT.PAKS_DWH_FACT_PSSPRT_BLCKLST (
    BLOCK_DATE, PASSPORT_NUM
) SELECT BLOCK_DATE, PASSPORT_NUM
    FROM PAKS_STG_PASSPORT_BLACKLIST
    WHERE BLOCK_DATE > (
        SELECT LAST_UPDATE_DT
        FROM DE3AT.PAKS_META_DATA
        WHERE SCHEMA_NAME='DE3AT' AND TABLE_NAME='PASSPORT_BLACKLIST'
    );

UPDATE DE3AT.PAKS_META_DATA
SET LAST_UPDATE_DT = (SELECT MAX(BLOCK_DATE) FROM DE3AT.PAKS_DWH_FACT_PSSPRT_BLCKLST)
WHERE SCHEMA_NAME='DE3AT' AND TABLE_NAME='PASSPORT_BLACKLIST';

COMMIT;